# Generated by Django 5.1.3 on 2024-11-25 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_bookreview_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='review',
            new_name='comment',
        ),
    ]
